name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04

    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:

      - name: Deploy to staging if develop branch
        if: ${{(github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/develop') || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop')}}
        run: curl -s ${{ secrets.ENVOYER_STAGING_TRIGGER }}

      - name: Deploy to prod if main branch
        if: ${{(github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main')}}
        run: |
          curl -s ${{ secrets.ENVOYER_PROD_TRIGGER }}
          curl -s ${{ secrets.ENVOYER_PROD_ASSET_HEALTH_TRIGGER }}
